// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tshyqizvsgvgrxygubqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzaHlxaXp2c2d2Z3J4eWd1YnFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NDQ3MTIsImV4cCI6MjA3MDEyMDcxMn0.d3leq9X11bUQmu07-Q7doYMCQkvwCkZ6E-NZCuzb0XE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});